version: '3'
services:
  seunghyo-mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DEV_PASSWORD}
      MYSQL_DATABASE: ${SEUNGHYO_DEV_DB_NAME}
      MYSQL_USER: ${SEUNGHYO_DEV_DB_USERNAME}
      MYSQL_PASSWORD: ${SEUNGHYO_DEV_DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - "3307:3306"
  seunghyo-redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6399:6379"

volumes:
  mysql-data:
    driver: local
  redis_data:
    driver: local