version: '3.7'
services:
  seunghyo-mysql:
    image: mysql:8.0
    container_name: seunghyo-mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: adele
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      TZ: Asia/Seoul
    secrets:
      - root_password
      - db_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --bind-address=0.0.0.0
  seunghyo-redis:
    image: redis:latest
    container_name: seunghyo-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 10s
      retries: 10
  seunghyo-zookeeper:
    image: bitnami/zookeeper:3.7.1
    container_name: seunghyo-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: [ "CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list" ]
      timeout: 10s
      retries: 10
  seunghyo-kafka:
    image: bitnami/kafka:3.4.0
    container_name: seunghyo-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://seunghyo-kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=seunghyo-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
      timeout: 10s
      retries: 10
    depends_on:
      seunghyo-zookeeper:
        condition: service_healthy
  seunghyo-eureka:
    build:
      context: ./app-eureka
      dockerfile: ./Dockerfile.dev
    container_name: seunghyo-eureka
    ports:
      - "8761:8761"
    restart: on-failure
  seunghyo-apigateway:
    build:
      context: ./app-apigateway
      dockerfile: ./Dockerfile.dev
    container_name: seunghyo-apigateway
    ports:
      - "8999:8999"
    # restart: on-failure
    environment:
      REDIS_DEV_HOST: seunghyo-redis
      REDIS_DEV_PORT: 6379
      ACCESS_TOKEN_VALIDITY_IN_SECONDS: 3600
      REFRESH_TOKEN_VALIDITY_IN_SECONDS: 604800
      EUREKA_SERVER_DEFAULT_ZONE: http://seunghyo-eureka:8761/eureka
    secrets:
      - jwt_secret
  seunghyo-member:
    build:
      context: .
      dockerfile: ./Dockerfile-app-member.dev
    container_name: seunghyo-member
    # restart: on-failure
    environment:
      EMAIL_USERNAME: seunghyoalgorithm
      ACCESS_TOKEN_VALIDITY_IN_SECONDS: 3600
      REFRESH_TOKEN_VALIDITY_IN_SECONDS: 604800
      MEMBER_SERVICE_DEV_DB_URL: seunghyo-mysql
      MEMBER_SERVICE_DEV_DB_PORT: 3306
      MEMBER_SERVICE_DEV_DB_NAME: member_service
      SEUNGHYO_DEV_DB_USERNAME: adele
      REDIS_DEV_HOST: seunghyo-redis
      REDIS_DEV_PORT: 6379
      EUREKA_SERVER_DEFAULT_ZONE: http://seunghyo-eureka:8761/eureka
    secrets:
      - email_password
      - db_password
      - jwt_secret
  seunghyo-problem:
    build:
      context: ./app-problem
      dockerfile: ./Dockerfile.dev
    container_name: seunghyo-problem
    # restart: on-failure
    environment:
      EMAIL_USERNAME: seunghyoalgorithm
      PROBLEM_SERVICE_DEV_DB_URL: seunghyo-mysql
      PROBLEM_SERVICE_DEV_DB_PORT: 3306
      PROBLEM_SERVICE_DEV_DB_NAME: problem_service
      SEUNGHYO_DEV_DB_USERNAME: adele
      REDIS_DEV_HOST: seunghyo-redis
      REDIS_DEV_PORT: 6379
      EUREKA_SERVER_DEFAULT_ZONE: http://seunghyo-eureka:8761/eureka
      COMPILER_JAVA11_BIN_PATH: /app/compiler-tools/jdk-11/bin
      PROBLEM_SERVICE_KAFKA_URL: seunghyo-kafka:9092
    secrets:
      - email_password
      - db_password
  seunghyo-board:
    build:
      context: ./app-board
      dockerfile: ./Dockerfile.dev
    container_name: seunghyo-board
    # restart: on-failure
    environment:
      EMAIL_USERNAME: seunghyoalgorithm
      BOARD_SERVICE_DEV_DB_URL: seunghyo-mysql
      BOARD_SERVICE_DEV_DB_PORT: 3306
      BOARD_SERVICE_DEV_DB_NAME: board_service
      SEUNGHYO_DEV_DB_USERNAME: adele
      REDIS_DEV_HOST: seunghyo-redis
      REDIS_DEV_PORT: 6379
      EUREKA_SERVER_DEFAULT_ZONE: http://seunghyo-eureka:8761/eureka
    secrets:
      - email_password
      - db_password

secrets:
  root_password:
    file: secret/root_dev_db_password.txt
  db_password:
    file: secret/seunghyo_dev_db_password.txt
  email_password:
    file: secret/email_password.txt
  jwt_secret:
    file: secret/jwt_secret.txt