version: '3'
services:
  seunghyo-oracle:
    image: gvenzl/oracle-xe:11
    container_name: oracle
    environment:
      ORACLE_PASSWORD: ${ROOT_DEV_PASSWORD}
      APP_USER: ${SEUNGHYO_DEV_DB_USERNAME}
      APP_USER_PASSWORD: ${SEUNGHYO_DEV_DB_PASSWORD}
    volumes:
      - oracle-volume:/u01/app/oracle/oradata
    ports:
      - "1522:1521"

  seunghyo-redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6399:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 24  # 메시지 보유 기간을 1일로 설정
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  oracle-volume:
    driver: local
  redis_data:
    driver: local