spring:
  application:
    name: SeungHyo-Backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_DB_URL}:${DEV_DB_PORT}/${SEUNGHYO_DEV_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${SEUNGHYO_DEV_DB_USERNAME}
    password: ${SEUNGHYO_DEV_DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}


server:
  port: ${SERVER_PORT:8999}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 60
  refresh-token-validity-in-seconds: 86400

cross-origin-url: http://localhost:3000

email-check-code-valid-in-seconds: 180 # 3분
