server:
  port: 0

spring:
  application:
    name: member-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MEMBER_SERVICE_DEV_DB_URL}:${MEMBER_SERVICE_DEV_DB_PORT}/${MEMBER_SERVICE_DEV_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${SEUNGHYO_DEV_DB_USERNAME}
    password: ${SEUNGHYO_DEV_DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_VALIDITY_IN_SECONDS}

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

email-check-code-valid-in-seconds: 180 # 3분
valid-email-time-in-seconds: 1800 # 30분