server:
  port: 8999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    web-application-type: reactive
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: app-gateway
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000' # 허용하려는 도메인
            allow-credentials: true # 요청 시 인증 정보를 전송하도록 허가
            allowedHeaders: '*' # 허용하려는 헤더
            allowedMethods: '*' # 허용하려는 HTTP 메서드
      routes:
        - id: app-member-logout
          uri: lb://APP-MEMBER
          predicates:
            - Path=/api/v1/member/auth/logout
          filters:
            - CustomLogoutFilter
        - id: app-member-auth
          uri: lb://APP-MEMBER
          predicates:
            - Path=/api/v1/member/auth/**
        - id: app-member-my
          uri: lb://APP-MEMBER
          predicates:
            - Path=/api/v1/member/**
          filters:
            - AuthorizationHeaderFilter
        - id: app-problem-get
          uri: lb://APP-PROBLEM
          predicates:
            - Path=/api/v1/problem/**
        - id: app-problem-language
          uri: lb://APP-PROBLEM
          predicates:
            - Path=/api/v1/programlanguage/**
        - id: app-submit-compile
          uri: lb://APP-SUBMIT
          predicates:
            - Path=/api/v1/compile
            - Method=POST
          filters:
            - AuthorizationHeaderFilter
        - id: app-problem-get-submit
          uri: lb://APP-PROBLEM
          predicates:
            - Path=/api/v1/submit/**
        - id: app-submit-compile-socket-service
          uri: lb:ws://APP-SUBMIT
          predicates:
            - Path=/submit/**
        - id: app-board-get-board
          uri: lb://APP-BOARD
          predicates:
            - Path=/api/v1/board/**
            - Method=GET
        - id: app-board-get-reply
          uri: lb://APP-BOARD
          predicates:
            - Path=/api/v1/reply/**
            - Method=GET
        - id: app-board-post-board
          uri: lb://APP-BOARD
          predicates:
            - Path=/api/v1/board
            - Method=POST
          filters:
            - AuthorizationHeaderFilter

jwt:
  secret: ${jwt_secret}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_VALIDITY_IN_SECONDS}