server:
  port: 0

spring:
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: problem-service
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${email_password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROBLEM_SERVICE_DEV_DB_URL}:${PROBLEM_SERVICE_DEV_DB_PORT}/${PROBLEM_SERVICE_DEV_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: ${SEUNGHYO_DEV_DB_USERNAME}
    password: ${db_password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}

compiler:
  java11-path: ${COMPILER_JAVA11_BIN_PATH}

kafka:
  url: ${PROBLEM_SERVICE_KAFKA_URL}