server:
  port: 8999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/auth/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/**
          filters:
            - AuthorizationHeaderFilter

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 60
  refresh-token-validity-in-seconds: 86400