server:
  port: 8999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/auth/logout
          filters:
            - CustomLogoutFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/auth/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/**
          filters:
            - AuthorizationHeaderFilter
        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/v1/problem/**
        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/v1/programlanguage/**
        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/v1/submit/**
          filters:
            - AuthorizationHeaderFilter

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_VALIDITY_IN_SECONDS}